### PR TITLE
fix(cmake): CblasConjNoTrans

### PR DESCRIPTION
**Pull request by Kolarovszki**
Before this patch it has been assumed that only MKL doesn't have
`CblasConjNoTrans`, but it turns out that it is independent of running
MKL or OpenBLAS, since on e.g. Arch Linux, the OpenBLAS packaging
doesn't include CBLAS, it should be installed separately, but the CBLAS
Arch package doesn't contain `CblasConjNoTrans`.

To resolve this, `CBLAS_CONJ_NO_TRANS_PRESENT` compilation flag is added
to `FindCBLAS.cmake`, since not every CBLAS has `CblasConjNoTrans`
present in the `CBLAS_TRANSPOSE` enum.

Since `vzConj` was originally an MKL function, the vector conjugation
is implemented in a separate `conjVector` function.

### CODE REVIEW

**Comment by rakytap** [comment]
I run performance tests. The test performance_tests/test_matrix.py gives me an error for checking the matrix products  A * B^* and A^* * B :)

**Comment by rakytap** [comment]
Also the test test_GaussianState.py does not pass correctly. I am using MKL as BLAS.

**Comment by rakytap** [comment]
The same tests fail if I use OpenBLAS

**Comment by Kolarovszki** [comment]
> Also the test test_GaussianState.py does not pass correctly. I am using MKL as BLAS.

Weird, `test_GaussianState.py` (and all the GaussianState-related tests) are successful at me but fail on `main`. `test_matrix.py::test_dot2` fails however, I'll correct it.

**Comment by rakytap** [comment]
Unfortunatelly, when run on virtual environment with MKL I am getting "Intel MKL ERROR: Parameter 2 was incorrect on entry to cblas_zgemm" when calculating A * B^* or A^* * B.  OpenBlas seems to work correctly.

**Pull request merged**
